spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/Levi_cart"
    username: "postgres"
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

#logging:
#  level:
#    org.hibernate: trace
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=jdbc:postgresql://localhost:5432/Levi_cart
#spring.datasource.username=postgres
#spring.datasource.password=0000
